### ISSUE TITLE
Is this usable?

### ISSUE THREAD

**Issue by jonom** [a-digital/eventbrite#1]
Hello, was looking for an Eventbrite plugin for Craft and found this. Tried to install `adigital/eventbrite` but it doesn't appear to be published yet (as noted in your ReadMe) - I was wondering how far you got with this plugin - can it be used? Thanks

**Comment by mark-adigital** [comment]
Hi - the plugin isn't yet published to the plugin store, but is functional. It was something we needed for a client and despite being completed, that project has not yet been able to go live.

The following screenshot of the settings page gives some indication of how it works - you provide your API key and organisation ID, and can optionally specify other event IDs to return along with your organisation's events. The settings page can be accessed by non-admins.. however, I believe I would need to add a custom model/record for the settings to fully support a project config workflow as the additional event IDs would need to be editable in a live environment where `allowAdminChanges` may be disabled. There's also scope for some user permissions to be added.

<img width="1037" alt="Screenshot 2019-09-06 at 10 04 28" src="https://user-images.githubusercontent.com/30312669/64416660-831b0e80-d08f-11e9-886d-af0825ff0bd3.png">

Once configured, the plugin variable can return all events sorted by date (belonging to the organisation and specified in the 'Other Events IDs' setting), just the organisation's or additional events on their own, a specific event by ID, venues belonging to the organisation, a venue by ID, and events taking place at a specific venue. The API is queried each time the data is returned, so you would need to wrap these in cache tags. A bigger update, but as you may have gathered all of those API calls are only to read data, so it would also be good to add event registration and payments etc. down the road.

I think that's a pretty good overview of where the plugin is currently at (I wrote it a few months ago now!) and we have been discussing releasing it recently, but right now I think we would hold off from publishing to the plugin store on either a paid or free basis as with other projects to complete, I can't guarantee when the above updates will happen. If the plugin sounds useful to you in its current form, you're welcome to download and use it as a [path repository](https://docs.craftcms.com/v3/extend/plugin-guide.html#loading-your-plugin-into-a-craft-project) on the basis of it being essentially a 'beta' release?

**Comment by jonom** [comment]
Thanks so much for the detailed reply! That answers my question so I could close this issue, but perhaps it's a good reference to leave around for others until you do a release?

**Comment by mark-adigital** [comment]
Just to let you know, I've now patched for Project Config and have released this plugin! I hope it may be of use to you and thanks for your interest.
