### ISSUE TITLE
Craft 4 Compatibility?

### ISSUE THREAD

**Issue by thoskam** [a-digital/eventbrite#12]
I tried to get this to run on Craft 4 but am running into too many issues. Is there a plan to update this plugin anytime soon for C4?

**Comment by aarmitage** [comment]
Yes, we have plans to release a Craft 4 compatible version by the end of July.

**Comment by thoskam** [comment]
Just checking to see if there is any update on this - We have a client who wants to launch their site early August so we're hopeful we can get this installed and configured relatively quickly.

**Comment by aarmitage** [comment]
Hi @thoskam - we're hoping to complete on it next week so we're slightly behind, but we should be able to release the update soon.

**Comment by thoskam** [comment]
is there a Beta for this we could download? We're willing to be your lab rat!

**Comment by aarmitage** [comment]
Thanks @thoskam - I think we're done - there'll be a release imminently, so thank you for your patience!

**Comment by mark-adigital** [comment]
Hey @thoskam - yep, I was working on the Craft 4 port last week which appears to be working fine for me on our demo site. If you are able to include the Craft 4 version in your site ahead of release for further testing, that would be hugely appreciated. You can do that by including this reference in your `composer.json` file:

`"adigital/eventbrite": "dev-master",`

And then running `composer update`.

Just let me know if you hit any bugs or problems.

**Comment by thoskam** [comment]
Thanks - I'm having an issue installing - I run composer update - and then
go to plugins and try to install and get the following error page:


![image](https://user-images.githubusercontent.com/2752547/183677990-744250ff-4c0d-44d0-8358-9b0df5e0e108.png)

**Comment by mark-adigital** [comment]
Thank you, I just committed a fix for that issue.

**Comment by thoskam** [comment]
Just letting you know I got it installed yesterday afternoon and everything seems to be working as expected. No bugs found so far!

**Comment by mark-adigital** [comment]
Excellent, thanks so much for that. Just released the plugin for Craft 4!
