### ISSUE TITLE
Moving "other" IDs causes them not to show up

### ISSUE THREAD

**Issue by dcplebranch** [a-digital/eventbrite#14]
I have a list of eventbrite IDs entered under "Other Event IDs" section. They all show up when I run the following query:

set events = craft.eventbrite.allEvents(['venue'], true, "current_future", false, "live")

I go back to the "Other Event IDs" page and I drag any of the IDs to a different position. Hit "Save".

When I go back to the page, using the same query (allEvents), none of the other IDs show up now!

A workaround to fix this: remove all other IDs... hit "Save".. then enter all the IDs again without moving any up or down.

Another thing that causes this same bug (and may be related). Instead of moving the IDs up or down, I hit the "x" to remove one of the IDs in the middle. Hit "Save". Now none of them show up. Removing the ID at the end doesn't cause this bug, only if the ID removed is in the middle of the list.

I am using Craft 3.7.52
Eventbrite 1.0.5
PHP 7.4.30

Any help appreciated.

**Comment by mark-adigital** [comment]
Hey @dcplebranch  - I think this is fixed in the most recent Craft 3 release, I'd actually already done it for Craft 4 and just needed to back port. Basically, how Craft iterates over these table settings changed so I had to amend a conditional around the loop accordingly.

**Comment by dcplebranch** [comment]
Thanks, this fixed it!
