### ISSUE TITLE
Error - Trying to access array offset on value of type null

### ISSUE THREAD

**Issue by JamesChristie200** [a-digital/eventbrite#16]
I have installed the plugin fine and added in the credentials.

Its only a testing account to try out this plugin before production.

Using private token for auth.

Im using the snippet you showed someone in a previous issue - 

`{% set events = craft.eventbrite.organisationEvents(null, "all", true) %}`

Craft CMS 3.7.63.1
PHP version | 7.4.33

Im assuming the plugin doesn't have to be payed for to work, as i'm only using for testing until i see it working. Testing in local environment too.

**Comment by JamesChristie200** [comment]
Ok figured out it was my organisation id was the problem, some conflicting advice on how to find it out you should clear that up in the docs.

**Comment by gracehcoote** [comment]
@JamesChristie200 sorry to jump on this thread, but I am not having any luck obtaining an organisation ID. Could you provide the steps you used to get yours?

**Comment by gjhead** [comment]
@JamesChristie200 How did you find your organisation id?  I'm having the same issue now that I have updated to Craft 4.

**Comment by gracehcoote** [comment]
@gjhead this should help, worked for me: 
https://github.com/a-digital/eventbrite/issues/7#issuecomment-1824414952
