### ISSUE TITLE
FR: Environment variables

### ISSUE THREAD

**Issue by thisiscap** [a-digital/eventbrite#18]
Could the admin fields be setup to take .env variables so the token isn't stored in version control?

**Comment by AdamADigital** [comment]
I have updated the main and craft3 branches with new releases, to allow for .env variables.
Eg, `$EVENTBRITE_AUTH_TOKEN` in the plugin config and `EVENTBRITE_AUTH_TOKEN=xxxx` in the .env file
They are v2.0.2 and v1.0.11 respectively.

@thisiscap let me know if there are any issues.
