### ISSUE TITLE
Unexpected token "operator" of value "="

### ISSUE THREAD

**Issue by zoinia** [a-digital/eventbrite#2]
I am new to twig, I need some help to understand what I am doing wrong.

Getting the following error when making a call with the following statment: 

```
{% set events = craft.eventbrite.organisationEvents([expansions] = null, time_filter = "all", unlistedEvents = true) %}
dd{{events}}
```

```
Twig Syntax Error – Twig\Error\SyntaxError
Arguments must be separated by a comma. Unexpected token "operator" of value "=" ("punctuation" expected with value ",").

```

Thank you

**Comment by matt-adigital** [comment]
Can you please try using the following code instead:

`{% set events = craft.eventbrite.organisationEvents(null, "all", true) %}`

The examples we've shown in our readme file denote the variable expected, followed by our default value. All you need to do is pass in the values themselves as per the example code I've provided in this response.

I hope that helps to resolve the errors you are experiencing.

**Comment by zoinia** [comment]
Perfect!! Thank you @matt-adigital
