### ISSUE TITLE
Calling unknown method: craft\web\twig\variables\CraftVariable::eventbrite()

### ISSUE THREAD

**Issue by wedot** [a-digital/eventbrite#4]
I have installed the plugin for eventbrite, but now I have the problem that I get the following message when I try to play the data in the frontend

`Calling unknown method: craft\web\twig\variables\CraftVariable::eventbrite()`

I also get an error message when I try to call the Dashboard Ad-On.
<img width="1022" alt="Bildschirmfoto 2020-01-25 um 17 16 23" src="https://user-images.githubusercontent.com/22647218/73124014-6e83d800-3f96-11ea-8051-b87eb8f99e7a.png">

Any ideas why is that?

**Comment by mark-adigital** [comment]
Hi @wedot  - have you configured the plugin with your auth token and organisation ID?

**Comment by wedot** [comment]
Yes i think so. I have tryed all Tokens. This tokens are in Craft.
 
The ID from the URL
The Client secret

 
<img width="387" alt="Bildschirmfoto 2020-01-29 um 09 29 34" src="https://user-images.githubusercontent.com/22647218/73340470-12150700-427b-11ea-919a-ec75e9b52a04.png">

<img width="1278" alt="Bildschirmfoto 2020-01-29 um 09 34 29" src="https://user-images.githubusercontent.com/22647218/73340293-c19da980-427a-11ea-9509-f9c2119882dc.png">

**Comment by mark-adigital** [comment]
It sounds like you may not have used the correct values, you can find your organisation ID as [described here](http://help.signaturesatori.com/en/articles/1002985-how-to-obtain-eventbrite-organizer-id) and the correct token to use is the Private token. Can you try these and see if that works please?

**Comment by wedot** [comment]
I have tested it with the Private token, but it don't works. The organisation ID should be right.
I use the numbers i have marked in the screenshot. (It's a other one this is a fake, this is just for showing that i did)
<img width="375" alt="Bildschirmfoto 2020-01-29 um 21 54 04" src="https://user-images.githubusercontent.com/22647218/73396569-f85ada80-42e1-11ea-82f5-05f450f92c48.png">

**Comment by wedot** [comment]
Okay, i don't know why but there is a other ID i have needed. I have to use the User ID and now it works...

**Comment by mark-adigital** [comment]
Thanks for persevering - I did look further into this and refactor some of the service logic to better handle if no events are found for an organiser.
