### ISSUE TITLE
Get address data over API

### ISSUE THREAD

**Issue by wedot** [a-digital/eventbrite#5]
First, thank you for the Plugin it's a cool one.

I wanted to pull the address over the API, but unfortunately this is not possible, because it is probably not accessible in the API. Can it be made available?

https://www.eventbrite.com/platform/api#/introduction/basic-types/address

**Comment by mark-adigital** [comment]
If you include `venue` as an expansion, you can access the address, eg.

`{% set event = craft.eventbrite.eventById(<eventID>, ["venue"]) %}`

Then in your template you can say:

`{{ event['venue']['address']['address_1'] }}`

Hope that helps

**Comment by mark-adigital** [comment]
Are you happy for me to close this issue now?

**Comment by wedot** [comment]
Is there no way to access the address without specifying an ID of Event? In a normal for loop? 

Linke this:
```
{% set events = craft.eventbrite.allEvents(null, true, "current_future", false, ["venue"]) %}
{% for event in events %}
   <div class="item">
      <a href="{{ event.url }}" target="_blank">
         {{ event.venue.address.address_1 }}
      </a>
   </div>
{% endfor %}
```

**Comment by wedot** [comment]
How can i set a `limit('6')` to the loop source?

**Comment by mark-adigital** [comment]
Yes.. If you [read the documentation](https://github.com/a-digital/eventbrite#the-plugin-variable), you can see how to pass expansions (such as the address) to any of the plugin methods.

Currently, there's no ability to limit the number of events returned.

**Comment by wedot** [comment]
Thank you.

The question is a bit direct now, but can you add the function to set a limit on the loop?  That would be a very helpful feature.

**Comment by mark-adigital** [comment]
No problem.

Ok - I've looked into this and it doesn't appear that I can set a limit on the request to the API (the best that offers is a limit per page). The other complication with that is that the limit of events to return from all the organisation events would depend on how many additional event IDs were specified. For that reason, I think the best approach would be to add limit parameters to the variable methods and then truncate the array returned as appropriate. This isn't ideal - it would be better to limit the data returned - but I'm not sure I can do it that way.

I'll look to make an update soon, but until I can, the best approach would be to limit your loop in the twig code - that won't be all that different from what I ultimately end up doing with PHP in the plugin anyway.
