### ISSUE TITLE
Error 404 retrieving data from Eventbrite: The path you requested does not exist.

### ISSUE THREAD

**Issue by lukehmu** [a-digital/eventbrite#8]
Hello,

I'm trying to get this working, but I'm having trouble with an error. My code is:
```
    {% set events = craft.eventbrite.allEvents(null, true, "current_future", false) %}
    <pre>
        {{ dump(events) }}
    </pre>
     {% for event in events %}
        {{ event }}
    {% endfor %}
```

I get this on the page:
![image](https://user-images.githubusercontent.com/1893145/91439285-a02e8b80-e864-11ea-978c-8aeadc23252d.png)

Thanks.

**Comment by mark-adigital** [comment]
Hi,

Sorry for the delay in coming back to you. I think the most likely culprit here is the organisation ID you have entered. Eventbrite really don't make it easy to find the correct value for this, but I've guided someone else in how to find it here: https://github.com/a-digital/eventbrite/issues/7#issuecomment-598124244

Hope that helps,

Mark

**Comment by mark-adigital** [comment]
Closing due lack of further feedback.
